/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Noir',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting_started' }],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    {
      type: 'category',
      label: 'Nargo',
      items: [{ type: 'autogenerated', dirName: 'nargo' }],
    },
    {
      type: 'category',
      label: 'Language Concepts',
      items: [{ type: 'autogenerated', dirName: 'language_concepts' }],
    },
    {
      type: 'category',
      label: 'Noir Standard Library',
      items: [
        {
          type: 'category',
          label: 'Cryptographic Primitives',
          link: {
            type: 'doc',
            id: 'standard_library/cryptographic_primitives',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'standard_library/cryptographic_primitives',
            },
          ],
        },
        'standard_library/array_methods',
        'standard_library/field_methods',
        'standard_library/logging',
        'standard_library/merkle_trees',
      ],
    },
    {
      type: 'category',
      label: 'Modules, Packages and Crates',
      items: [{ type: 'autogenerated', dirName: 'modules_packages_crates' }],
    },
    {
      type: 'doc',
      id: 'typescript',
      label: 'Working with Typescript',
    },
  ],
};

module.exports = sidebars;
